USE task_management_system;

SET @org_id = (SELECT id FROM organizations WHERE slug = 'pt-tenaga-kanggo-indonesia');
SET @password_hash = '$argon2id$v=19$m=65536,t=3,p=4$YKzVDqR0pJhVJT3KYnXRwg$8hJ0vV5lKZFqNxGxKpE2nYxKGQBzDc7S8LqXJhPvQnA';

INSERT INTO users (organization_id, email, password_hash, name, status, is_email_verified) VALUES
(@org_id, 'user1@kanggo.test', @password_hash, 'Ahmad Pratama', 'active', 1),
(@org_id, 'user2@kanggo.test', @password_hash, 'Budi Wijaya', 'active', 1),
(@org_id, 'user3@kanggo.test', @password_hash, 'Citra Santoso', 'active', 1),
(@org_id, 'user4@kanggo.test', @password_hash, 'Dewi Kusuma', 'active', 1),
(@org_id, 'user5@kanggo.test', @password_hash, 'Eko Permata', 'active', 1),
(@org_id, 'user6@kanggo.test', @password_hash, 'Fajar Nugraha', 'active', 1),
(@org_id, 'user7@kanggo.test', @password_hash, 'Gita Saputra', 'active', 1),
(@org_id, 'user8@kanggo.test', @password_hash, 'Hadi Utama', 'active', 1),
(@org_id, 'user9@kanggo.test', @password_hash, 'Indah Wibowo', 'active', 1),
(@org_id, 'user10@kanggo.test', @password_hash, 'Joko Setiawan', 'active', 1),
(@org_id, 'user11@kanggo.test', @password_hash, 'Kartika Hartono', 'active', 1),
(@org_id, 'user12@kanggo.test', @password_hash, 'Lina Gunawan', 'active', 1),
(@org_id, 'user13@kanggo.test', @password_hash, 'Made Hidayat', 'active', 1),
(@org_id, 'user14@kanggo.test', @password_hash, 'Novi Sudiro', 'active', 1),
(@org_id, 'user15@kanggo.test', @password_hash, 'Oki Prabowo', 'active', 1),
(@org_id, 'user16@kanggo.test', @password_hash, 'Putra Adiputra', 'active', 1),
(@org_id, 'user17@kanggo.test', @password_hash, 'Ratna Dharma', 'active', 1),
(@org_id, 'user18@kanggo.test', @password_hash, 'Sari Kusnandar', 'active', 1),
(@org_id, 'user19@kanggo.test', @password_hash, 'Tono Mahendra', 'active', 1),
(@org_id, 'user20@kanggo.test', @password_hash, 'Udin Prasojo', 'active', 1),
(@org_id, 'user21@kanggo.test', @password_hash, 'Vina Wijaya', 'active', 1),
(@org_id, 'user22@kanggo.test', @password_hash, 'Wati Santoso', 'active', 1),
(@org_id, 'user23@kanggo.test', @password_hash, 'Yudi Kusuma', 'active', 1),
(@org_id, 'user24@kanggo.test', @password_hash, 'Zaki Permata', 'active', 1),
(@org_id, 'user25@kanggo.test', @password_hash, 'Ahmad Nugraha', 'active', 1),
(@org_id, 'user26@kanggo.test', @password_hash, 'Budi Saputra', 'active', 1),
(@org_id, 'user27@kanggo.test', @password_hash, 'Citra Utama', 'active', 1),
(@org_id, 'user28@kanggo.test', @password_hash, 'Dewi Wibowo', 'active', 1),
(@org_id, 'user29@kanggo.test', @password_hash, 'Eko Setiawan', 'active', 1),
(@org_id, 'user30@kanggo.test', @password_hash, 'Fajar Hartono', 'active', 1),
(@org_id, 'user31@kanggo.test', @password_hash, 'Gita Gunawan', 'active', 1),
(@org_id, 'user32@kanggo.test', @password_hash, 'Hadi Hidayat', 'active', 1),
(@org_id, 'user33@kanggo.test', @password_hash, 'Indah Sudiro', 'active', 1),
(@org_id, 'user34@kanggo.test', @password_hash, 'Joko Prabowo', 'active', 1),
(@org_id, 'user35@kanggo.test', @password_hash, 'Kartika Adiputra', 'active', 1),
(@org_id, 'user36@kanggo.test', @password_hash, 'Lina Dharma', 'active', 1),
(@org_id, 'user37@kanggo.test', @password_hash, 'Made Kusnandar', 'active', 1),
(@org_id, 'user38@kanggo.test', @password_hash, 'Novi Mahendra', 'active', 1),
(@org_id, 'user39@kanggo.test', @password_hash, 'Oki Prasojo', 'active', 1),
(@org_id, 'user40@kanggo.test', @password_hash, 'Putra Pratama', 'active', 1),
(@org_id, 'user41@kanggo.test', @password_hash, 'Ratna Wijaya', 'active', 1),
(@org_id, 'user42@kanggo.test', @password_hash, 'Sari Santoso', 'active', 1),
(@org_id, 'user43@kanggo.test', @password_hash, 'Tono Kusuma', 'active', 1),
(@org_id, 'user44@kanggo.test', @password_hash, 'Udin Permata', 'active', 1),
(@org_id, 'user45@kanggo.test', @password_hash, 'Vina Nugraha', 'active', 1),
(@org_id, 'user46@kanggo.test', @password_hash, 'Wati Saputra', 'active', 1),
(@org_id, 'user47@kanggo.test', @password_hash, 'Yudi Utama', 'active', 1),
(@org_id, 'user48@kanggo.test', @password_hash, 'Zaki Wibowo', 'active', 1),
(@org_id, 'user49@kanggo.test', @password_hash, 'Ahmad Setiawan', 'active', 1),
(@org_id, 'user50@kanggo.test', @password_hash, 'Budi Hartono', 'active', 1),
(@org_id, 'user51@kanggo.test', @password_hash, 'Citra Gunawan', 'active', 1),
(@org_id, 'user52@kanggo.test', @password_hash, 'Dewi Hidayat', 'active', 1),
(@org_id, 'user53@kanggo.test', @password_hash, 'Eko Sudiro', 'active', 1),
(@org_id, 'user54@kanggo.test', @password_hash, 'Fajar Prabowo', 'active', 1),
(@org_id, 'user55@kanggo.test', @password_hash, 'Gita Adiputra', 'active', 1),
(@org_id, 'user56@kanggo.test', @password_hash, 'Hadi Dharma', 'active', 1),
(@org_id, 'user57@kanggo.test', @password_hash, 'Indah Kusnandar', 'active', 1),
(@org_id, 'user58@kanggo.test', @password_hash, 'Joko Mahendra', 'active', 1),
(@org_id, 'user59@kanggo.test', @password_hash, 'Kartika Prasojo', 'active', 1),
(@org_id, 'user60@kanggo.test', @password_hash, 'Lina Pratama', 'active', 1),
(@org_id, 'user61@kanggo.test', @password_hash, 'Made Wijaya', 'active', 1),
(@org_id, 'user62@kanggo.test', @password_hash, 'Novi Santoso', 'active', 1),
(@org_id, 'user63@kanggo.test', @password_hash, 'Oki Kusuma', 'active', 1),
(@org_id, 'user64@kanggo.test', @password_hash, 'Putra Permata', 'active', 1),
(@org_id, 'user65@kanggo.test', @password_hash, 'Ratna Nugraha', 'active', 1),
(@org_id, 'user66@kanggo.test', @password_hash, 'Sari Saputra', 'active', 1),
(@org_id, 'user67@kanggo.test', @password_hash, 'Tono Utama', 'active', 1),
(@org_id, 'user68@kanggo.test', @password_hash, 'Udin Wibowo', 'active', 1),
(@org_id, 'user69@kanggo.test', @password_hash, 'Vina Setiawan', 'active', 1),
(@org_id, 'user70@kanggo.test', @password_hash, 'Wati Hartono', 'active', 1),
(@org_id, 'user71@kanggo.test', @password_hash, 'Yudi Gunawan', 'active', 1),
(@org_id, 'user72@kanggo.test', @password_hash, 'Zaki Hidayat', 'active', 1),
(@org_id, 'user73@kanggo.test', @password_hash, 'Ahmad Sudiro', 'active', 1),
(@org_id, 'user74@kanggo.test', @password_hash, 'Budi Prabowo', 'active', 1),
(@org_id, 'user75@kanggo.test', @password_hash, 'Citra Adiputra', 'active', 1),
(@org_id, 'user76@kanggo.test', @password_hash, 'Dewi Dharma', 'active', 1),
(@org_id, 'user77@kanggo.test', @password_hash, 'Eko Kusnandar', 'active', 1),
(@org_id, 'user78@kanggo.test', @password_hash, 'Fajar Mahendra', 'active', 1),
(@org_id, 'user79@kanggo.test', @password_hash, 'Gita Prasojo', 'active', 1),
(@org_id, 'user80@kanggo.test', @password_hash, 'Hadi Pratama', 'active', 1),
(@org_id, 'user81@kanggo.test', @password_hash, 'Indah Wijaya', 'active', 1),
(@org_id, 'user82@kanggo.test', @password_hash, 'Joko Santoso', 'active', 1),
(@org_id, 'user83@kanggo.test', @password_hash, 'Kartika Kusuma', 'active', 1),
(@org_id, 'user84@kanggo.test', @password_hash, 'Lina Permata', 'active', 1),
(@org_id, 'user85@kanggo.test', @password_hash, 'Made Nugraha', 'active', 1),
(@org_id, 'user86@kanggo.test', @password_hash, 'Novi Saputra', 'active', 1),
(@org_id, 'user87@kanggo.test', @password_hash, 'Oki Utama', 'active', 1),
(@org_id, 'user88@kanggo.test', @password_hash, 'Putra Wibowo', 'active', 1),
(@org_id, 'user89@kanggo.test', @password_hash, 'Ratna Setiawan', 'active', 1),
(@org_id, 'user90@kanggo.test', @password_hash, 'Sari Hartono', 'active', 1),
(@org_id, 'user91@kanggo.test', @password_hash, 'Tono Gunawan', 'active', 1),
(@org_id, 'user92@kanggo.test', @password_hash, 'Udin Hidayat', 'active', 1),
(@org_id, 'user93@kanggo.test', @password_hash, 'Vina Sudiro', 'active', 1),
(@org_id, 'user94@kanggo.test', @password_hash, 'Wati Prabowo', 'active', 1),
(@org_id, 'user95@kanggo.test', @password_hash, 'Yudi Adiputra', 'active', 1),
(@org_id, 'user96@kanggo.test', @password_hash, 'Zaki Dharma', 'active', 1),
(@org_id, 'user97@kanggo.test', @password_hash, 'Ahmad Kusnandar', 'active', 1),
(@org_id, 'user98@kanggo.test', @password_hash, 'Budi Mahendra', 'active', 1),
(@org_id, 'user99@kanggo.test', @password_hash, 'Citra Prasojo', 'active', 1),
(@org_id, 'user100@kanggo.test', @password_hash, 'Dewi Pratama', 'active', 1);

SET @user_role_id = (SELECT id FROM roles WHERE code = 'user' AND organization_id = @org_id);
SET @admin_role_id = (SELECT id FROM roles WHERE code = 'admin' AND organization_id = @org_id);
SET @first_user_id = (SELECT id FROM users WHERE email = 'user1@kanggo.test');

INSERT INTO user_roles (user_id, role_id, organization_id) 
SELECT id, @admin_role_id, @org_id FROM users WHERE email = 'user1@kanggo.test'
UNION ALL
SELECT id, @user_role_id, @org_id FROM users WHERE email LIKE 'user%@kanggo.test' AND id != @first_user_id;
